component_depth: 1
languages:
 - java
exclude:
 - /docs/.*
 - /sdk/.*
 - /sdk-test/.*
 - /environment/settings/.*.java
 - /environment/target/.*.java
 - /environment/src/test/java/tygronenv/MyEnvListener.java
 - /environment/src/test/java/tygronenv/TestEnvironment.java
 - /environment/src/test/java/tygronenv/TestEnvironmentStates.java
 - /environment/src/test/java/tygronenv/settings/.*.java
 - /environment/src/main/java/tygronenv/connection/ServerConnection.java
 - /environment/src/main/java/tygronenv/connection/Session.java
 - /environment/src/main/java/tygronenv/EisEnv.java
 - /environment/src/main/java/tygronenv/EntityEventHandler.java
 - /environment/src/main/java/tygronenv/tygronEntity.java
 - /environment/src/main/java/tygronenv/translators/J2ActionLog.java
 - /environment/src/main/java/tygronenv/translators/J2ActionMenu.java
 - /environment/src/main/java/tygronenv/translators/J2Answer.java
 - /environment/src/main/java/tygronenv/translators/J2Category.java
 - /environment/src/main/java/tygronenv/translators/J2ClientItemMap.java
 - /environment/src/main/java/tygronenv/translators/J2Function.java
 - /environment/src/main/java/tygronenv/translators/J2Indicator.java
 - /environment/src/main/java/tygronenv/translators/J2Land.java
 - /environment/src/main/java/tygronenv/translators/J2MultiPolygon.java
 - /environment/src/main/java/tygronenv/translators/J2PopupData.java
 - /environment/src/main/java/tygronenv/translators/J2Setting.java
 - /environment/src/main/java/tygronenv/translators/J2Stakeholder.java
 - /environment/src/main/java/tygronenv/translators/J2TimeState.java
 - /environment/src/main/java/tygronenv/translators/J2Zone.java
 - /environment/src/test/java/tygronenv/translators/J2ClientItemMapTest.java
 - /environment/src/test/java/tygronenv/translators/J2IndicatorTest.java
 - /environment/src/test/java/tygronenv/translators/J2StakeholderTest.java
 - /environment/src/test/java/tygronenv/translators/J2ZoneTest.java
 - /environment/src/main/java/tygronenv/translators/HashMap2J.java
 - /environment/src/main/java/tygronenv/translators/MultiPolygon2J.java
 - /environment/src/main/java/tygronenv/translators/ParamEnum2J.java
 - /environment/src/main/java/tygronenv/translators/Stakeholder2J.java
 - /environment/src/test/java/tygronenv/translators/HashMap2JTest.java
 - /environment/src/test/java/tygronenv/translators/MultiPolygon2JTest.java
 - /environment/src/test/java/tygronenv/translators/ParamEnum2JTest.java
 - /environment/src/test/java/tygronenv/translators/Stakeholder2JTest.java
 - /environment/src/test/java/tygronenv/translators/TranslatorsTest.java