language: java

language: java
install: mvn -pl "!doc" install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- java -cp environment/target/tygronenv-*-jar-with-dependencies.jar login.Login $email $password
- mvn test
jdk:
- oraclejdk8

notifications:
  slack:
    secure: Pe+b90XtvFSZirnHsVFSibmEPfUfB4F2CcuNm32JAEsklQ3Dlat8+Fz2FWXZFqveLnSSzYssK59LpWewmXkg/UOECnIDsVBh+C70n6QCUjxS1UIhviECop8CrRcU1k7kysfoWqF1wVeXs5q0vujb99uunFjAkr2+0Lolfke5+6Tzixg0WGxuutPW519nbLpXfIR5V/0oKL6eky+18HTwFMX8OLxUM9nS5TiHB6J/tGYFMFSfjQoPZK0izsdD323WkX9l+8oIrVaXVWWmCGDFu83r6VOtg1hWB0EN/BbWIYyE94yeT+Ctn8MDS05LFC//VTP6VLgKsUbZgzbtIrHVg7htFKy9cWux0L9gZiqcVShTFj1pRzmTGksywgsU7YpwLHO5jGAvhI49W7b1bRpR9YM8sW1NsiwJyfGzEmqKfhLPNY5gQtUPtMMoauudO4PzXzFrwtyk9oOtNvZ1BCh0nMK6Vo9NaiNY2jfRVzK4YcMs5q0Dvw611T4Sit5B+isvEUsK7Jyz2mskke5CWXhAjpprqNW1StKqkA8eVLtB4paQhkuHXAtRGhCTZgqn2vStecq/py1KIMt3E5UXWKaoXg3mDWUCszl+BSrzarybYu+D7CBo8LOPtEtpQdK1PH68F3zHSkwxxxHLE0IdkMilzkplVQmsv9HDqhJU+hB/eXo=
